### ISSUE TITLE
Exception thrown when content picker value is node with unpublished parent

### ISSUE THREAD

**Issue by karlmacklin** [nikcio/Nikcio.UHeadless#143]
Using UHeadless version 2.2.0

## Recreating scenario:

Add a simple document type with a single field in form of a node picker. Make it creatable in root and inherit itself as permissions.
Create the following node structure:

```
root
\-- page1
|     \--page2
|
\-- testpage
```

Make sure page2 is published, and have page1 be unpublished.
The slug for page2 should now be `/page1/page2`.

On the testpage, pick page2 as the content in the content picker.

Try to get the page via graphql query:

```
query myquery {
  contentByAbsoluteRoute(
    route: "/testpage"
  ) {
    properties {
      alias
      value
    }
  }
}
```

## Expected result:
Null or empty value for the content picker.

## Actual result:

An exception is thrown. GraphQL results:

```
{
  "errors": [
    {
      "message": "Exception has been thrown by the target of an invocation.",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "contentByAbsoluteRoute",
        "properties",
        0,
        "value"
      ]
    }
  ],
  "data": {
    "contentByAbsoluteRoute": {
      "properties": [
        {
          "alias": "pickern",
          "value": null
        }
      ]
    }
  }
}
```

Dotnet runtime logged error is:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Unable to cast object of type 'Umbraco.Cms.Core.GuidUdi' to type 'System.Collections.Generic.IEnumerable`1[Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent]'.
   at Nikcio.UHeadless.UmbracoElements.Properties.EditorsValues.ContentPicker.BasicContentPicker`1..ctor(CreatePropertyValue createPropertyValue, IDependencyReflectorFactory dependencyReflectorFactory)
   at Nikcio.UHeadless.UmbracoElements.Properties.EditorsValues.ContentPicker.BasicContentPicker..ctor(CreatePropertyValue createPropertyValue, IDependencyReflectorFactory dependencyReflectorFactory)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Nikcio.UHeadless.Reflection.Factories.DependencyReflectorFactory.GetReflectedType[T](Type typeToReflect, Object[] constructorRequiredParamerters)
   at Nikcio.UHeadless.UmbracoElements.Properties.Factories.PropertyValueFactory.GetPropertyValue(CreatePropertyValue createPropertyValue)
   at Nikcio.UHeadless.UmbracoElements.Properties.Models.BasicProperty.get_Value()
   at HotChocolate.Execution.Processing.Tasks.ResolverTaskFactory.<ResolveAndCompleteInline>g__TryExecute|4_0(Object& result, <>c__DisplayClass4_0& )
```

**This error does not trigger on multinode tree picker!**

**Comment by karlmacklin** [comment]
If I wrap the field inside a blocklist editor the returned error changes slightly:

```
{
  "errors": [
    {
      "message": "Exception has been thrown by the target of an invocation.",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "contentByAbsoluteRoute",
        "properties",
        0,
        "value"
      ],
      "extensions": {
        "code": "EXEC_INVALID_LEAF_VALUE"
      }
    }
  ],
  "data": {
    "contentByAbsoluteRoute": {
      "properties": [
        {
          "alias": "blocklistan",
          "value": null
        }
      ]
    }
  }
}
```

And in the Log Viewer we see:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Unable to cast object of type 'Umbraco.Cms.Core.GuidUdi' to type 'System.Collections.Generic.IEnumerable`1[Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent]'.
   at Nikcio.UHeadless.UmbracoElements.Properties.EditorsValues.ContentPicker.BasicContentPicker`1..ctor(CreatePropertyValue createPropertyValue, IDependencyReflectorFactory dependencyReflectorFactory)
   at Nikcio.UHeadless.UmbracoElements.Properties.EditorsValues.ContentPicker.BasicContentPicker..ctor(CreatePropertyValue createPropertyValue, IDependencyReflectorFactory dependencyReflectorFactory)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Nikcio.UHeadless.Reflection.Factories.DependencyReflectorFactory.GetReflectedType[T](Type typeToReflect, Object[] constructorRequiredParamerters)
   at Nikcio.UHeadless.UmbracoElements.Properties.Factories.PropertyValueFactory.GetPropertyValue(CreatePropertyValue createPropertyValue)
   at Nikcio.UHeadless.UmbracoElements.Properties.Models.BasicProperty.get_Value()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitObject(Object obj, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitValue(Object obj, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitList(ICollection list, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitValue(Object obj, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitObject(Object obj, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitValue(Object obj, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitList(ICollection list, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitValue(Object obj, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitObject(Object obj, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.VisitValue(Object obj, Action`1 setValue, ISet`1 processed)
   at HotChocolate.Utilities.ObjectToDictionaryConverter.Convert(Object obj)
   at HotChocolate.Types.AnyType.TrySerialize(Object runtimeValue, Object& resultValue)
   at HotChocolate.Types.ScalarType.Serialize(Object runtimeValue)
   at HotChocolate.Execution.Processing.ValueCompletion.TryCompleteLeafValue(IOperationContext operationContext, MiddlewareContext resolverContext, ISelection selection, Path path, IType fieldType, Object result, Object& completedResult)
```

**Comment by nikcio** [comment]
Status: Working theory is that Umbraco returns weird unexpected data.

Details:
```
System.InvalidCastException: Unable to cast object of type 'Umbraco.Cms.Core.GuidUdi' to type 'System.Collections.Generic.IEnumerable`1[Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent]'.
```

Comes from:
https://github.com/nikcio/Nikcio.UHeadless/blob/v4/contrib/src/Nikcio.UHeadless.Base/Basics/EditorsValues/ContentPicker/Models/BasicContentPicker.cs#L45

Umbraco docs shows that an `IPublishedContent` should be returned: https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/content-picker

**Comment by nikcio** [comment]
**Note:** #147 fixes this for v4 and beyond. A temporary fix will still need to be implemented for v3 and maybe v2 😄 

I think a change to: 
https://github.com/nikcio/Nikcio.UHeadless/blob/3099520c00b4d5de60edda2c5cbce5b7434d3c53/src/Nikcio.UHeadless.Base/Basics/EditorsValues/ContentPicker/Models/BasicContentPicker.cs#L43

Like this:
```csharp
} else if (objectValue != null)
```

```csharp
} else if (objectValue is IEnumerable<IPublishedContent> contentItems)
```

Would do the trick but I'll need to test it on the v3 branch.

**Comment by nikcio** [comment]
@karlmacklin I've now validated the solution on v2 & v3. The fix is included in:
- v2.3.1
- v3.3.1
